self.image_viewer_frame_1 = self.findChild(QFrame, 'image1')
        self.components_viewer_frame_1 = self.findChild(QFrame, 'image1Frequancy')
        self.image_viewer_1 = ImageViewer()
        self.image_viewer_frame_1_layout = QVBoxLayout()
        self.components_viewer_1 = ComponentViewer()
        self.components_viewer_frame_1_layout = QVBoxLayout()
        self.components_viewer_frame_1.setLayout(self.components_viewer_frame_1_layout)
        self.components_viewer_frame_1_layout.addWidget(self.components_viewer_1)
        self.image_viewer_frame_1.setLayout(self.image_viewer_frame_1_layout)
        self.image_viewer_frame_1_layout.addWidget(self.image_viewer_1)
        
        self.image_viewer_frame_2 = self.findChild(QFrame, 'image2')
        self.components_viewer_frame_2 = self.findChild(QFrame, 'image2Frequency')
        self.image_viewer_2 = ImageViewer()
        self.image_viewer_frame_2_layout = QVBoxLayout()
        self.components_viewer_2 = ComponentViewer()
        self.components_viewer_frame_2_layout = QVBoxLayout()
        self.components_viewer_frame_2.setLayout(self.components_viewer_frame_2_layout)
        self.components_viewer_frame_2_layout.addWidget(self.components_viewer_2)
        self.image_viewer_frame_2.setLayout(self.image_viewer_frame_2_layout)
        self.image_viewer_frame_2_layout.addWidget(self.image_viewer_2)
        
        self.image_viewer_frame_3 = self.findChild(QFrame, 'image3')
        self.components_viewer_frame_3 = self.findChild(QFrame, 'image3Frequency')
        self.image_viewer_3 = ImageViewer()
        self.image_viewer_frame_3_layout = QVBoxLayout()
        self.components_viewer_3 = ComponentViewer()
        self.components_viewer_frame_3_layout = QVBoxLayout()
        self.components_viewer_frame_3.setLayout(self.components_viewer_frame_3_layout)
        self.components_viewer_frame_3_layout.addWidget(self.components_viewer_3)
        self.image_viewer_frame_3.setLayout(self.image_viewer_frame_3_layout)
        self.image_viewer_frame_3_layout.addWidget(self.image_viewer_3)
        
        self.image_viewer_frame_4 = self.findChild(QFrame, 'image4')
        self.components_viewer_frame_4 = self.findChild(QFrame, 'image4Frequency')
        self.image_viewer_4 = ImageViewer()
        self.image_viewer_frame_4_layout = QVBoxLayout()
        self.components_viewer_4 = ComponentViewer()
        self.components_viewer_frame_4_layout = QVBoxLayout()
        self.components_viewer_frame_4.setLayout(self.components_viewer_frame_4_layout)
        self.components_viewer_frame_4_layout.addWidget(self.components_viewer_4)
        self.image_viewer_frame_4.setLayout(self.image_viewer_frame_4_layout)
        self.image_viewer_frame_4_layout.addWidget(self.image_viewer_4)
        
        self.output_viewer_frame_1 = self.findChild(QFrame, 'output1Frame')
        self.output_viewer_1 = ImageViewer()
        self.output_viewer_frame_1_layout = QVBoxLayout()
        self.output_viewer_frame_1.setLayout(self.output_viewer_frame_1_layout)
        self.output_viewer_frame_1_layout.addWidget(self.output_viewer_1)
        
        self.output_viewer_frame_2 = self.findChild(QFrame, 'output2Frame')
        self.output_viewer_2 = ImageViewer()
        self.output_viewer_frame_2_layout = QVBoxLayout()
        self.output_viewer_frame_2.setLayout(self.output_viewer_frame_2_layout)
        self.output_viewer_frame_2_layout.addWidget(self.output_viewer_2)
        self.image_viewer_frame_4 = self.findChild(QFrame, 'image4')
        self.components_viewer_frame_4 = self.findChild(QFrame, 'image4Frequancy')